# Generated by Django 5.0.4 on 2024-04-30 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcard',
            name='borrowed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
