# Generated by Django 5.0.4 on 2024-04-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryWeb', '0002_alter_visitorcard_borrowed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcard',
            name='borrowed_date',
            field=models.DateTimeField(),
        ),
    ]
